### PR TITLE
Rethrow errors in Proxy accessors (GH#14)

### LINKED ISSUE #14: Fix cryptic error
I got a cryptic error in my tests `Ge.fail is not a function`, and tracked it down to a line in [inspect.js](https://github.com/hildjj/node-inspect-extracted/blob/6cf5c1fff1ca3ca44a6be93834b71630f2c3cbc2/src/inspect.js#L1558). I feel like this should be changed to `assert(err.stack)` or `throw err` or something.

If it's relevant, I'm calling `format()` on a proxy object that I use for testing.

Thanks for this package btw!

### PR DESCRIPTION
**Pull request by nmay231**
Closes #14

I put the test in [test-util-inspect.js](https://github.com/hildjj/node-inspect-extracted/compare/main...nmay231:node-inspect-extracted:rethrow-accessor-errors?expand=1#diff-755e2936fb30a27966acf7a34f5e4f73478d2a19a6bed3372586a7421b43d4b1) but I could move it to a new file in `test/internal` or something, if you wish.

### CODE REVIEW

**Comment by nmay231** [comment]
Sidenote: Do you export your wrapper around Proxy that directly formats its target object when passed to inspect? It's not showing up in my typescript project, so the types might need to be updated. (I can probably do that)

**Comment by hildjj** [comment]
Yes, please move that test to somewhere outside of the `parallel` directory.  I try to keep those in sync with the node source.  

Feel free to update the types also, although I should be doing that every time I update.  Start here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/util.d.ts

Yes, Proxy should be in the types file. along with stylizeWithColor and stylizeWithHTML.  Perhaps the whole set of type changes should be a separate PR?

**Comment by nmay231** [comment]
I'll provide the types separately :+1:

**Comment by nmay231** [comment]
Bump

**Comment by hildjj** [comment]
Sorry!  Will likely get to this Monday.

**Review by hildjj — APPROVED** [review]

**Pull request merged**
