### PR TITLE
Include InspectOptions interface

### PR DESCRIPTION
**Pull request by anodynos**
Thanks for this lib - just what I needed. 
The  `InspectOptions` interface was missing somehow, added here. I've tested in my IDE, it works.

### CODE REVIEW

**Comment by nmay231** [comment]
`InspectOptions` is a type, not an object; there is nothing exported from the javascript file called `InspectOptions`. Try logging it in your IDE. I expect you will get `undefined`.

You might want the object `inspectDefaultOptions`. (I'm writing a PR that includes this in the types, so you could wait for that version).

If you do just want the type/interface `InspectOptions`, it's already exported as a type from `types/util.d.ts` in the latest version (try updating the package if you don't have it right now).

**Comment by hildjj** [comment]
Fixed by #17 I think.

**Comment by anodynos** [comment]
> `InspectOptions` is a type, not an object; there is nothing exported from the javascript file called `InspectOptions`. Try logging it in your IDE. I expect you will get `undefined`.
> 
> You might want the object `inspectDefaultOptions`. (I wrote a PR #17 that includes this export in the types, so you could wait for that to be released).
> 
> If you do just want the type/interface `InspectOptions`, it's already exported as a type from `types/util.d.ts` in the latest version (try updating the package if you don't have it right now).

Yes, it's not compiled for JavaScript, but you need the type in TypeScript if for example you need to reference it, extend it etc

**Comment by nmay231** [comment]
@anodynos In that case, it's already exported from `utils.d.ts`. You don't export types from a `js` or `mjs` file:

https://github.com/hildjj/node-inspect-extracted/blob/c14396d6ce41d43a71cc0961bc23fad89705a337/types/util.d.ts#L14

I can import `InspectOptions` just fine in my project (using version `2.0.0`), so something else is up. Would you open up an issue with these details, please?

What version of `node-inspect-extracted` are you using, and what's your `tsconfig.json`?

**Pull request closed without merging**
